### ISSUE TITLE
driver/MotoPlus: bHasPreviousData set but never used?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#138]
The variable `bHasPreviousData` introduced in d23afc85ed5cd11b5c3648241e75e798862b0580 seems to be set ([here](https://github.com/ros-industrial/motoman/blob/e13b2bb156f3db57789669a16cedb12839d3efd4/motoman_driver/MotoPlus/MotionServer.c) and [here](https://github.com/ros-industrial/motoman/blob/e13b2bb156f3db57789669a16cedb12839d3efd4/motoman_driver/MotoPlus/MotionServer.c)), but is then never used anywhere as far as I can tell.

Assuming the "*Allow for multiple packets to be received in single Recv command*" line in the commit message of d23afc85ed5cd11b5c3648241e75e798862b0580 is actually related, should `bHasPreviousData` be included in any of the conditionals in `MotionServer::Ros_MotionServer_WaitForSimpleMsg(..)`?

**Comment by ted-miller** [comment]
You are correct.  I missed a line in a previous merge.  I'll fix it this afternoon.  But, before I try another commit, can you review my previous one so that I don't screw it up further...?

![image](https://cloud.githubusercontent.com/assets/4623811/21525159/4e752bb8-cce9-11e6-89e0-c21f3c21ffe9.png)

**Comment by ted-miller** [comment]
This has been corrected in PR 140.

**Comment by gavanderhoorn** [comment]
Thanks for the fix, but let's keep this open until #140 has been merged.

**Comment by gavanderhoorn** [comment]
Fixed in 40896603425f73b98b2b3b3631d5b367c61fae4d.
