### ISSUE TITLE
motoman_sia*_support Warnings caused by deprecated tag in package.xml files

### ISSUE THREAD

**Issue by dambrosio** [ros-industrial/motoman#261]
```bash
WARNING: Package 'motoman_sia10d_support' is deprecated (This package will be removed in ROS Kinetic. The configuration data and
      models included in this package can now be found in the motoman_sia_support
      package in ROS Jade.)
WARNING: Package 'motoman_sia10f_support' is deprecated (This package will be removed in ROS Kinetic. The configuration data and
      models included in this package can now be found in the motoman_sia_support
      package in ROS Jade.)
WARNING: Package 'motoman_sia20d_support' is deprecated (This package will be removed in ROS Kinetic. The configuration data and
      models included in this package can now be found in the motoman_sia_support
      package in ROS Jade.)
WARNING: Package 'motoman_sia5d_support' is deprecated (This package will be removed in ROS Kinetic. The configuration data and
      models included in this package can now be found in the motoman_sia_support
      package in ROS Jade.)
```
Thoughts on what we should do for `kinetic-devel`? These packages are still in the `kinetic-devel` branch and are actually not combined in `jade-devel`? Is there a reason they were deprecated?

I fixed by throwing a CATKIN_IGNORE into each motoman_sia* package but I am only interested in the `motoman_driver`.

**Comment by gavanderhoorn** [comment]
At the time these deprecation notices were added an effort was underway to setup robot support packages in this repository the same way as we do in ROS-I for other brands: put as many variants of the same robot series in a single package, naming the package after the series, not the variant (and to clean things up: there isn't really something like an SIA20D or SIA20F: only the controller differs, but that's not something the support pkgs capture).

Hence the notice that says to look for `motoman_sia_support` (which was to contain all SIA variants: 5, 10, 20 and 50). See #82 for that.

With the merge of #212, this policy was abandoned and it was decided that each robot variant should get its own package. The deprecation notices were never removed from the pkg manifests though, which is why you see them now.

The situation is confusing now and the packages in this repository (and `motoman_experimental`) could use some attention. It's been on the list, but we've not been able to get to it.

> I fixed by throwing a CATKIN_IGNORE into each motoman_sia* package but I am only interested in the `motoman_driver`.

If you're using `catkin_tools` I would recommend using its blacklist feature.
