### ISSUE TITLE
Document supported series & variants

### ISSUE THREAD

**Issue by Gaspard-Bourgeois** [ros-industrial/motoman#373]
Does anyone can add in the Readme.md the Yaskawa commercial names compatible for each package. For instance the MA1440 match the package of "motomam_m12_support". Does a list exists somewhere ?

Thanks a lot for your help.

**Comment by gavanderhoorn** [comment]
No, we don't have such a list.

The general convention in ROS-Industrial is to create so called *robot support packages*, which would contain all the variants of a specific robot series or model.

For Motoman robots however, robot support packages almost always support only a single robot variant. So `motoman_mh12_support` supports just the MH12 and `motoman_gp12_support` supports just the GP12.

The only exceptions right now (in this repository) are `motoman_hc10_support`, which supports both the base model and the `DT` variant and `motoman_hc20_support`, which supports the base model and the `DT` and `XP` variants.

So to figure out which package supports which robot:

 1. look at the name of the package and determine which robot variant it supports
 1. take a look at the `package.xml` of that package, specifically the `description`

If specific support packages could also be used for other series or variants, that could be documented in the package manifest.

**Comment by gavanderhoorn** [comment]
Could I ask you to change the title of your issue? Right now it's quite unclear how it relates to the actual question.

**Comment by EricMarcil** [comment]
Your suggesting is noted.  
It is true that in recent year, some models have multiple names for marketing reasons.  For example, the MH12 is the same as the MA1440.  MH12 refers to Material Handling with a payload of 12 kg, whereas MA1440 refers to Material ArcWelding with a reach of 1440 mm but with a 6 kg payload.  But even if it is the same arm, the parameters are different, the MA1440 has higher-max speed and acceleration since the maximum payload is lower.
We usually use the General or Handling name of the model on the ROS site because we haven't seen much ArcWelding application though we are starting to see some.
Normally both appelation of the robot would be present in the identification plate on the robot. 
If you don't have access to the physical robot, then look at the motoman.com website.  When a robot has multiple names, it usually has only one manual.  So if you look for the manual of the robot you are interested in, on the cover you will also see reference to the other model names. But check the specifications, their maybe differences on the range. max speed and acceleration.

**Comment by EricMarcil** [comment]
I updated my previous comment because even if models are physically the same, there may be variations in parameters, so we have to be careful before saying to models are the same.  We might be able to put them in the same support package but you might need different URDF to account for the specification variations.

**Comment by Gaspard-Bourgeois** [comment]
Thanks a lot for those precisions and have a great end of year.
