### ISSUE TITLE
about support for SIA30D 

### ISSUE THREAD

**Issue by xuhuairuogu** [ros-industrial/motoman#406]
Thanks for providing such a good ROS package for motoman control. However, I do not find motoman_sia30d_support directory. I wanna know if motoman_sia30d can be normally driven by the driver within this package. If yes, are you planning to write support files for motoman_sia30d? if no, what modifications I can make on this package?

**Comment by gavanderhoorn** [comment]
> I wanna know if motoman_sia30d can be normally driven by the driver within this package

the driver -- as all drivers in `ros-industrial` -- is largely manipulator agnostic, meaning it should be usable with all robots which are supported by the controllers which this driver supports.

Summarising: yes, you should be able to use it with an SIA30.

>  If yes, are you planning to write support files for motoman_sia30d? 

I don't believe we have plans specific to the SIA30, but if there is demand we can see whether that could be added.

Creating a support package isn't *that* difficult btw. It would come down to creating files similar to `motoman_sia50d_support` (for instance), updating names, replacing the meshes and updating the `xacro:macro` (correct `link`s, `joint`s, etc).

**Comment by EricMarcil** [comment]
The SIA30 is a modified version of the SIA50 where extension were added between the links to increase reach (which reduced the payload from 50 kg to 30 kg).
We did not have plan to support this robot since it is already several generation old (and no one has asked for it), but I can assist you if you need it.
You can probably take a copy of GP50D model and rename it.  Then adjust the values in the urdf/sia30_macro.xacro.
You'll get some gaps between the link but that could be filled by a cylinder.  I can try to get the model but it may take a couple of weeks.
Below are the values for the sia30d.  Angle should be fine, just adjust the are links and the various limits.
![image](https://user-images.githubusercontent.com/4691677/118495363-22135d00-b6f1-11eb-82ec-be057d43323c.png)

**Comment by gavanderhoorn** [comment]
@xuhuairuogu: could you indicate whether you're still interested in adding support for the SIA30?

**Comment by xuhuairuogu** [comment]
> @xuhuairuogu: could you indicate whether you're still interest in adding support for the SIA30?

yes. Since I am not very good at handling 3D models, it would be a great help for me if you could add support for the SIA30.

**Comment by gavanderhoorn** [comment]
@EricMarcil wrote:
>  I can try to get the model but it may take a couple of weeks.

@EricMarcil: could you request the meshes please?

**Comment by EricMarcil** [comment]
Yes, I've put in a request for the model.  I'll try to put the model together once I have the mesh.

**Comment by EricMarcil** [comment]
I've create PR #411 to add the SIA30D model.
@xuhuairuogu : Please review the model and let me know if there are any problems.
