### ISSUE TITLE
Torque readings from DX200 are not continuous.

### ISSUE THREAD

**Issue by nexus1203** [ros-industrial/motoman#507]
After following the instructions on this comment #174, I collected the torque data using two method, first the controller torque method another is the Mregister method. However both the methods return torque readings with a significant delay. However, Joint readings are still continuous. I am hoping devs can shed some light on this, if this is a controller limitation? I have ordered MotoPlus from the local dealership. I am hoping that may solve the issue. However, the comparisons are attached as follow.
The joint angles are in pulse. sorry for the label.
[DX200_torque.csv](https://github.com/ros-industrial/motoman/files/8942602/DX200_torque.csv)
![DX200_torque](https://user-images.githubusercontent.com/70212520/174652311-adf95fbb-5c5b-4210-9a48-180c250086c6.png)

[DX200_Mregister.csv](https://github.com/ros-industrial/motoman/files/8942603/DX200_Mregister.csv)
![DX200_Mregister](https://user-images.githubusercontent.com/70212520/174652351-3bf49972-5751-46a8-b59a-4154d1f56c25.png)

**Comment by ted-miller** [comment]
Hi @nexus1203 
I think what you're seeing is caused by the frequency that feedback data is published from motoros to motoman_driver.

https://github.com/ros-industrial/motoman/blob/7860ff545106d98ed6a3fa0121f2fb60891f69bd/motoman_driver/MotoPlus/StateServer.h#L35

>  I have ordered MotoPlus from the local dealership

With the SDK, you can decrease the `STATE_UPDATE_MIN_PERIOD` and you should see immediate improvement.
