### ISSUE TITLE
Alarm 8004 TASK #0 MOTOROS FAILED TO CREATE TASK [4]

### ISSUE THREAD

**Issue by leitoxve** [ros-industrial/motoman#525]
Hello everyone, 
My setup is a yaskawa HC20 with  yrc1000 Controller  
I follow the instruction for (.out - .JBI -.DAT ) [Installing INFORM Code] installation like as:
http://wiki.ros.org/motoman_driver/Tutorials/indigo/InstallServer
and i launch the streaming interface
https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_hc20_support/launch/robot_interface_streaming_hc20.launch
and immediately the teach pendant show Alarm 8004 TASK #0 MOTOROS FAILED TO CREATE TASK [4] Like picture:
![image](https://user-images.githubusercontent.com/44784957/201707769-d32afd2b-a4f0-42df-8e9e-1a434ef45fa1.png)
my CLI spit out this 
![image](https://user-images.githubusercontent.com/44784957/201713367-4c4a21e4-497f-41f1-bed6-ede76c4afb4c.png)
 
I suspect it is a double thread or connection and when i search the robot backend  thread i find this:
![image](https://user-images.githubusercontent.com/44784957/201713990-8d324a90-0642-4745-bb95-f15a24dcaa94.png)

but I dont know..... Can you help me please???
with love from listembourg!! XD

**Comment by ted-miller** [comment]
Hi @leitoxve.
The alarm 8004 [4] means that the system was unable to create the task which submits motion increments to the MotoPlus API. 

That task runs at priority level `MP_PRI_IP_CLK_TAKE`. There can only be one task in the whole system which runs at this priority level. In your case, that priority is already being used by the `CommTest.out` application. 
![image](https://user-images.githubusercontent.com/4623811/201736238-53bb3507-0a40-44a2-aee5-58d4d0dd3c28.png)

I recommend that you delete the `CommTest.out` application in MAINTENANCE mode. But if you want to keep that application installed, then please edit the code so that the task runs at priority level `MP_PRI_TIME_NORMAL`.

Let me know if you have any additional questions.
