### ISSUE TITLE
Motoman Ros I/O read/write error

### ISSUE THREAD

**Issue by Avgrobo** [ros-industrial/motoman#571]
We're trying to control Festo make gripper integrated with Yaskawa GP12 robot via ROS using rosservice. On calling the service execution error states that Its illegal to write or read the address. 
![control error](https://github.com/ros-industrial/motoman/assets/45308643/9aad4b63-ece7-444b-8add-b861b370c33e)

Kindly support on resolving the error to control.
Thanks

**Comment by gavanderhoorn** [comment]
First: please don't post screenshots of terminal output. It's all text, so please copy-paste it into a [fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) instead.

Having written that: every robot controller supported by MotoROS1 only allows a few ranges of addresses to be written to. See the service documentation for information:

https://github.com/ros-industrial/motoman/blob/70d731cb9e6cec3e116a4aedafdf19da140b8839/motoman_msgs/srv/WriteSingleIO.srv#L2-L15

PS: and you most likely already know, but ROS Melodic has been EOL [since June this year](http://wiki.ros.org/Distributions#List_of_Distributions), so will not see any updates nor enhancements any more.
